  
version: 2.1

jobs:
    build:
        docker:
            - image: cimg/base:2020.01
        steps:
            - checkout
            - run: ./validate.sh
            - run: echo This should run!
workflows:
    version: 2
    default:
        jobs: 
            - build